// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4U8vVyYm7Qx6VMDQQvYb0DEveK2UjHX4',
    appId: '1:678004364037:web:9e9f32b0cb096dbafe1d6c',
    messagingSenderId: '678004364037',
    projectId: 'gtx-app-f7488',
    authDomain: 'gtx-app-f7488.firebaseapp.com',
    storageBucket: 'gtx-app-f7488.firebasestorage.app',
    measurementId: 'G-XSEFJJRZ8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl7k2n0gGGtuVQDaahry4PFasAaWMPvzk',
    appId: '1:678004364037:android:f52712291dfe04a2fe1d6c',
    messagingSenderId: '678004364037',
    projectId: 'gtx-app-f7488',
    storageBucket: 'gtx-app-f7488.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPZKYo9AYWBeXQryqI99_ly1t2r8-Ghrg',
    appId: '1:678004364037:ios:d8a61d286fa4c7a4fe1d6c',
    messagingSenderId: '678004364037',
    projectId: 'gtx-app-f7488',
    storageBucket: 'gtx-app-f7488.firebasestorage.app',
    iosBundleId: 'com.example.gtxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPZKYo9AYWBeXQryqI99_ly1t2r8-Ghrg',
    appId: '1:678004364037:ios:d8a61d286fa4c7a4fe1d6c',
    messagingSenderId: '678004364037',
    projectId: 'gtx-app-f7488',
    storageBucket: 'gtx-app-f7488.firebasestorage.app',
    iosBundleId: 'com.example.gtxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4U8vVyYm7Qx6VMDQQvYb0DEveK2UjHX4',
    appId: '1:678004364037:web:70cb1a32aa95ada7fe1d6c',
    messagingSenderId: '678004364037',
    projectId: 'gtx-app-f7488',
    authDomain: 'gtx-app-f7488.firebaseapp.com',
    storageBucket: 'gtx-app-f7488.firebasestorage.app',
    measurementId: 'G-TNBTE2XMXX',
  );
}
